# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader
from embedding import *

document_path = "new-Policies.txt"
loader = TextLoader(document_path)
documents = loader.load()

chunks = text_splitter.split_documents(documents)
# Id the chunks
ids = [str(i) for i in range(0, len(chunks))]

vectordb = Chroma.from_documents(chunks, watsonx_embedding, ids=ids)

query = "Email policy"
# Maximal Marginal Relevance
retriever = vectordb.as_retriever(search_type="mmr", search_kwargs={"k": 2})
docs = retriever.invoke(query)
print(docs)