# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader
from embedding import *

document_path = "new-Policies.txt"
loader = TextLoader(document_path)
documents = loader.load()

chunks = text_splitter.split_documents(documents)
print(f"Total no. of chunks = {len(chunks)}")

# Id the chunks
ids = [str(i) for i in range(0, len(chunks))]

vectordb = Chroma.from_documents(chunks, watsonx_embedding, ids=ids)

query = "Smoking policy"
docs = vectordb.similarity_search(query, k=5)
print(docs)